import type { IUser } from '../types/user.types';

export const dummyUsers: IUser[] = [
  {
    id: 1,
    firstName: 'Emily',
    lastName: 'Johnson',
    email: 'emily.johnson@x.dummyjson.com',
    phone: '+81 965-431-3024',
    age: 28,
    gender: 'female',
    role: 'admin',
    image: 'https://dummyjson.com/icon/emilys/128',
    birthDate: '1996-5-30',
    university: 'University of Wisconsin--Madison',
    address: {
      address: '626 Main Street',
      city: 'Phoenix',
      state: 'Arizona',
      country: 'United States',
    },
    company: {
      name: 'Dooley, Kozey and Cronin',
      department: 'Engineering',
      title: 'Sales Manager',
    },
  },
  {
    id: 2,
    firstName: 'Michael',
    lastName: 'Williams',
    email: 'michael.williams@x.dummyjson.com',
    phone: '+49 258-627-6644',
    age: 35,
    gender: 'male',
    role: 'user',
    image: 'https://dummyjson.com/icon/michaelw/128',
    birthDate: '1989-8-10',
    university: 'Stanford University',
    address: {
      address: '123 Elm Street',
      city: 'Austin',
      state: 'Texas',
      country: 'United States',
    },
    company: {
      name: 'Blanda-O\'Keefe',
      department: 'Marketing',
      title: 'Marketing Director',
    },
  },
  {
    id: 3,
    firstName: 'Sophia',
    lastName: 'Brown',
    email: 'sophia.brown@x.dummyjson.com',
    phone: '+44 892-123-4567',
    age: 24,
    gender: 'female',
    role: 'editor',
    image: 'https://dummyjson.com/icon/sophiab/128',
    birthDate: '2000-2-15',
    university: 'University of Cambridge',
    address: {
      address: '456 Oak Lane',
      city: 'London',
      state: 'England',
      country: 'United Kingdom',
    },
    company: {
      name: 'Hintz Group',
      department: 'Content',
      title: 'Senior Editor',
    },
  },
  {
    id: 4,
    firstName: 'James',
    lastName: 'Davis',
    email: 'james.davis@x.dummyjson.com',
    phone: '+1 345-678-9012',
    age: 42,
    gender: 'male',
    role: 'admin',
    image: 'https://dummyjson.com/icon/jamesd/128',
    birthDate: '1982-11-05',
    university: 'Harvard University',
    address: {
      address: '789 Pine Road',
      city: 'Seattle',
      state: 'Washington',
      country: 'United States',
    },
    company: {
      name: 'Kuhn-Gusikowski',
      department: 'Operations',
      title: 'Operations Manager',
    },
  },
  {
    id: 5,
    firstName: 'Isabella',
    lastName: 'Miller',
    email: 'isabella.miller@x.dummyjson.com',
    phone: '+61 456-789-0123',
    age: 31,
    gender: 'female',
    role: 'user',
    image: 'https://dummyjson.com/icon/isabellam/128',
    birthDate: '1993-4-20',
    university: 'University of Melbourne',
    address: {
      address: '321 Maple Avenue',
      city: 'Sydney',
      state: 'New South Wales',
      country: 'Australia',
    },
    company: {
      name: 'Rohan-Larkin',
      department: 'Sales',
      title: 'Sales Representative',
    },
  },
  {
    id: 6,
    firstName: 'William',
    lastName: 'Wilson',
    email: 'william.wilson@x.dummyjson.com',
    phone: '+81 567-890-1234',
    age: 29,
    gender: 'male',
    role: 'user',
    image: 'https://dummyjson.com/icon/williamw/128',
    birthDate: '1995-7-12',
    university: 'University of Tokyo',
    address: {
      address: '654 Cedar Blvd',
      city: 'Tokyo',
      state: 'Tokyo',
      country: 'Japan',
    },
    company: {
      name: 'Wyman-Boyle',
      department: 'Engineering',
      title: 'Software Engineer',
    },
  },
  {
    id: 7,
    firstName: 'Olivia',
    lastName: 'Moore',
    email: 'olivia.moore@x.dummyjson.com',
    phone: '+49 678-901-2345',
    age: 38,
    gender: 'female',
    role: 'editor',
    image: 'https://dummyjson.com/icon/oliviam/128',
    birthDate: '1986-9-25',
    university: 'Technical University of Munich',
    address: {
      address: '987 Birch Way',
      city: 'Berlin',
      state: 'Berlin',
      country: 'Germany',
    },
    company: {
      name: 'Gleichner, Zieme and Lueilwitz',
      department: 'Design',
      title: 'Lead Designer',
    },
  },
  {
    id: 8,
    firstName: 'Benjamin',
    lastName: 'Taylor',
    email: 'benjamin.taylor@x.dummyjson.com',
    phone: '+44 789-012-3456',
    age: 27,
    gender: 'male',
    role: 'user',
    image: 'https://dummyjson.com/icon/benjamint/128',
    birthDate: '1997-1-08',
    university: 'University of Oxford',
    address: {
      address: '147 Walnut St',
      city: 'Manchester',
      state: 'England',
      country: 'United Kingdom',
    },
    company: {
      name: 'Kerluke-Kreiger',
      department: 'Support',
      title: 'Support Specialist',
    },
  },
  {
    id: 9,
    firstName: 'Ava',
    lastName: 'Anderson',
    email: 'ava.anderson@x.dummyjson.com',
    phone: '+1 890-123-4567',
    age: 33,
    gender: 'female',
    role: 'admin',
    image: 'https://dummyjson.com/icon/avaa/128',
    birthDate: '1991-6-18',
    university: 'Massachusetts Institute of Technology',
    address: {
      address: '258 Ash Court',
      city: 'Boston',
      state: 'Massachusetts',
      country: 'United States',
    },
    company: {
      name: 'Schamberger-Upton',
      department: 'HR',
      title: 'HR Director',
    },
  },
  {
    id: 10,
    firstName: 'Alexander',
    lastName: 'Thomas',
    email: 'alexander.thomas@x.dummyjson.com',
    phone: '+61 901-234-5678',
    age: 45,
    gender: 'male',
    role: 'editor',
    image: 'https://dummyjson.com/icon/alexandert/128',
    birthDate: '1979-3-22',
    university: 'University of Sydney',
    address: {
      address: '369 Spruce Pl',
      city: 'Brisbane',
      state: 'Queensland',
      country: 'Australia',
    },
    company: {
      name: 'Bayer and Sons',
      department: 'Finance',
      title: 'Financial Analyst',
    },
  },
  {
    id: 11,
    firstName: 'Mia',
    lastName: 'Jackson',
    email: 'mia.jackson@x.dummyjson.com',
    phone: '+81 012-345-6789',
    age: 26,
    gender: 'female',
    role: 'user',
    image: 'https://dummyjson.com/icon/miaj/128',
    birthDate: '1998-10-14',
    university: 'Kyoto University',
    address: {
      address: '741 Fir Drive',
      city: 'Osaka',
      state: 'Osaka',
      country: 'Japan',
    },
    company: {
      name: 'Stark-Daugherty',
      department: 'Marketing',
      title: 'Social Media Manager',
    },
  },
  {
    id: 12,
    firstName: 'Ethan',
    lastName: 'White',
    email: 'ethan.white@x.dummyjson.com',
    phone: '+49 123-456-7890',
    age: 39,
    gender: 'male',
    role: 'admin',
    image: 'https://dummyjson.com/icon/ethanw/128',
    birthDate: '1985-12-02',
    university: 'Humboldt University of Berlin',
    address: {
      address: '852 Willow Blvd',
      city: 'Munich',
      state: 'Bavaria',
      country: 'Germany',
    },
    company: {
      name: 'Leuschke-Harris',
      department: 'IT',
      title: 'Systems Administrator',
    },
  }
];
